// <auto-generated />
using DataSql;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataSql.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231107174701_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("DataSql.Classes.Instrument", b =>
                {
                    b.Property<string>("Identifier")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("InstrumentType")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Identifier");

                    b.ToTable("Instrument");
                });

            modelBuilder.Entity("DataSql.Classes.InstrumentType", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("InstrumentType");
                });
#pragma warning restore 612, 618
        }
    }
}
